name: First Workflow

on: workflow_dispatch # Manual trigger

jobs: 

  first-job: # Name of job, not a reserved word
    runs-on: ubuntu-latest
    steps:
      - name: 01 Print greeting
        run: echo "Hello Creepy World!!!"
      - name: 02 Print goodbye
        run: echo "That's all Folks!!"
